import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import LoginBtn from './LoginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import LogoutBtn from './LogoutBtn';
export const dynamic = 'force-dynamic';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  let gitSession = await getServerSession(authOptions); ///회원 정보 가져오기
  let kakaoSession = await getServerSession(authOptions);

  const session = gitSession || kakaoSession;
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='navbar flex justify-between'>
          <div>
            <Link href='/' className='logo'>
              MyBlog
            </Link>
            <Link href='/list'>List</Link>
            <Link href='/write'>Write</Link>
            {/* jsx에서는 삼항 연산자 사용 가능  */}
          </div>

          <div>
            {session ? (
              <span>
                반갑습니다! {session.user.name} 님 <LogoutBtn />
              </span>
            ) : (
              <LoginBtn />
            )}
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
